require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.null-ls"
spec "user.illuminate"
spec "user.telescope"
spec "user.telescope-tabs"
spec "user.nvimtree"
spec "user.lualine"
spec "user.whichkey"
spec "user.cmp"
spec "user.autopairs"
spec "user.comment"
spec "user.gitsigns"
spec "user.neogit"
spec "user.diffview"
spec "user.indentline"
spec "user.alpha"
spec "user.netrw"
spec "user.project"
spec "user.toggleterm"
spec "user.bufdelete"
-- Added by Rafa
spec "user.plenary"
spec "user.vimtex"
spec "user.sved"
spec "user.lastplace"
spec "user.gutentags"
spec "user.surround"
-- Python REPL...
-- Warning: bug detected, spell not working when jukit plugin installed
-- spec "user.jukit"
-- spec "user.jupynium"
spec "user.codeium" -- spec "user.copilot"
spec "user.molten"
-- ... python REPL end
spec "user.bito-ai"
spec "user.notify"
spec "user.markdown"
require "user.lazy"

